sudo: required
services:
- docker
before_install:
- docker login -u="${QUAY_USER}" -p="${QUAY_PASSWORD}" quay.io
script:
- 9/ci.sh
notifications:
  slack:
    secure: I01kvX71vWivneJVHCN6vlSM4rFJU2Awi3uXn24ZtuAeFN1DCp+GLkRBzcVeRAKQcA3WYPemWbJgYPCkBfprl1gxcatCoBcey2Vv4cYyXOy62dgHDAyeD040VNgA94u5h/Fkd6T0cW1ankCSIMP90tZcwE2YS3ba9I5S1S8v0ao=
